//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoOffBot.Api.WhosOff {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", ConfigurationName="Api.WhosOff.WhosOffPublicSoap")]
    public interface WhosOffPublicSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (WhosOff) of message WhosOff does not match the default value (WHOSOFF)
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/WhosOff", ReplyAction="*")]
        WhoOffBot.Api.WhosOff.WhosOff1 WHOSOFF(WhoOffBot.Api.WhosOff.WhosOff request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/WhosOff", ReplyAction="*")]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.WhosOff1> WHOSOFFAsync(WhoOffBot.Api.WhosOff.WhosOff request);
        
        // CODEGEN: Generating message contract since the wrapper name (WhosOffByCompany) of message WhosOffByCompany does not match the default value (WHOSOFF1)
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/WhosOffByCompany", ReplyAction="*")]
        WhoOffBot.Api.WhosOff.WhosOffByCompany1 WHOSOFF1(WhoOffBot.Api.WhosOff.WhosOffByCompany request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/WhosOffByCompany", ReplyAction="*")]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.WhosOffByCompany1> WHOSOFF1Async(WhoOffBot.Api.WhosOff.WhosOffByCompany request);
        
        // CODEGEN: Generating message contract since the wrapper name (WhosOffByStaff) of message WhosOffByStaff does not match the default value (WHOSOFF_BY_STAFFID)
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/WhosOffByStaff", ReplyAction="*")]
        WhoOffBot.Api.WhosOff.WhosOffByStaff1 WHOSOFF_BY_STAFFID(WhoOffBot.Api.WhosOff.WhosOffByStaff request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/WhosOffByStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.WhosOffByStaff1> WHOSOFF_BY_STAFFIDAsync(WhoOffBot.Api.WhosOff.WhosOffByStaff request);
        
        // CODEGEN: Generating message contract since the wrapper name (WhosOffByDepartment) of message WhosOffByDepartment does not match the default value (WHOSOFF_BY_DEPARTMENT)
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/WhosOffByDepartment", ReplyAction="*")]
        WhoOffBot.Api.WhosOff.WhosOffByDepartment1 WHOSOFF_BY_DEPARTMENT(WhoOffBot.Api.WhosOff.WhosOffByDepartment request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/WhosOffByDepartment", ReplyAction="*")]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.WhosOffByDepartment1> WHOSOFF_BY_DEPARTMENTAsync(WhoOffBot.Api.WhosOff.WhosOffByDepartment request);
        
        // CODEGEN: Generating message contract since the wrapper name (WhosOffByLeaveType) of message WhosOffByLeaveType does not match the default value (WHOSOFF_BY_LEAVE_TYPE)
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/WhosOffByLeaveType", ReplyAction="*")]
        WhoOffBot.Api.WhosOff.WhosOffByLeaveType1 WHOSOFF_BY_LEAVE_TYPE(WhoOffBot.Api.WhosOff.WhosOffByLeaveType request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/WhosOffByLeaveType", ReplyAction="*")]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.WhosOffByLeaveType1> WHOSOFF_BY_LEAVE_TYPEAsync(WhoOffBot.Api.WhosOff.WhosOffByLeaveType request);
        
        // CODEGEN: Generating message contract since the wrapper name (StaffDetails) of message StaffDetails does not match the default value (STAFF_DETAILS)
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/StaffDetails", ReplyAction="*")]
        WhoOffBot.Api.WhosOff.StaffDetails1 STAFF_DETAILS(WhoOffBot.Api.WhosOff.StaffDetails request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/StaffDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.StaffDetails1> STAFF_DETAILSAsync(WhoOffBot.Api.WhosOff.StaffDetails request);
        
        // CODEGEN: Generating message contract since the wrapper name (StaffDetailsMinimum) of message StaffDetailsMinimum does not match the default value (STAFF_DETAILS1)
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/StaffDetailsMinimum", ReplyAction="*")]
        WhoOffBot.Api.WhosOff.StaffDetailsMinimum1 STAFF_DETAILS1(WhoOffBot.Api.WhosOff.StaffDetailsMinimum request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/StaffDetailsMinimum", ReplyAction="*")]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.StaffDetailsMinimum1> STAFF_DETAILS1Async(WhoOffBot.Api.WhosOff.StaffDetailsMinimum request);
        
        // CODEGEN: Generating message contract since the wrapper name (Staff_x0020_Details_x0020_By_x0020_StaffID) of message Staff_x0020_Details_x0020_By_x0020_StaffID does not match the default value (STAFF_DETAILS_BY_STAFFID)
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/Staff Details By StaffID", ReplyAction="*")]
        WhoOffBot.Api.WhosOff.StaffDetailsByStaffID1 STAFF_DETAILS_BY_STAFFID(WhoOffBot.Api.WhosOff.StaffDetailsByStaffID request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/Staff Details By StaffID", ReplyAction="*")]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.StaffDetailsByStaffID1> STAFF_DETAILS_BY_STAFFIDAsync(WhoOffBot.Api.WhosOff.StaffDetailsByStaffID request);
        
        // CODEGEN: Generating message contract since the wrapper name (Staff_x0020_Details_x0020_By_x0020_StaffID_x0020_inclucing_x0020_Company_x0020_Year) of message Staff_x0020_Details_x0020_By_x0020_StaffID_x0020_inclucing_x0020_Company_x0020_Year does not match the default value (STAFF_DETAILS_BY_STAFFID1)
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/Staff Details By StaffID inclucin" +
            "g Company Year", ReplyAction="*")]
        WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDinclucingCompanyYear1 STAFF_DETAILS_BY_STAFFID1(WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDinclucingCompanyYear request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/Staff Details By StaffID inclucin" +
            "g Company Year", ReplyAction="*")]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDinclucingCompanyYear1> STAFF_DETAILS_BY_STAFFID1Async(WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDinclucingCompanyYear request);
        
        // CODEGEN: Generating message contract since the wrapper name (StaffDetailsByStaffID) of message StaffDetailsByStaffID does not match the default value (STAFF_DETAILS_BY_DEPARTMENT)
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/StaffDetailsByStaffID", ReplyAction="*")]
        WhoOffBot.Api.WhosOff.StaffDetailsByStaffID3 STAFF_DETAILS_BY_DEPARTMENT(WhoOffBot.Api.WhosOff.StaffDetailsByStaffID2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/StaffDetailsByStaffID", ReplyAction="*")]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.StaffDetailsByStaffID3> STAFF_DETAILS_BY_DEPARTMENTAsync(WhoOffBot.Api.WhosOff.StaffDetailsByStaffID2 request);
        
        // CODEGEN: Generating message contract since the wrapper name (Staff_x0020_Details_x0020_By_x0020_StaffID_x0020_including_x0020_Company_x0020_Year) of message Staff_x0020_Details_x0020_By_x0020_StaffID_x0020_including_x0020_Company_x0020_Year does not match the default value (STAFF_DETAILS_BY_DEPARTMENT1)
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/Staff Details By StaffID includin" +
            "g Company Year", ReplyAction="*")]
        WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDincludingCompanyYear1 STAFF_DETAILS_BY_DEPARTMENT1(WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDincludingCompanyYear request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/Staff Details By StaffID includin" +
            "g Company Year", ReplyAction="*")]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDincludingCompanyYear1> STAFF_DETAILS_BY_DEPARTMENT1Async(WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDincludingCompanyYear request);
        
        // CODEGEN: Generating message contract since element name APIKEY from namespace http://publicapi.whosoff.com/WhosOffPublic.asmx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/LEAVE_TYPES", ReplyAction="*")]
        WhoOffBot.Api.WhosOff.LEAVE_TYPESResponse LEAVE_TYPES(WhoOffBot.Api.WhosOff.LEAVE_TYPESRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/LEAVE_TYPES", ReplyAction="*")]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.LEAVE_TYPESResponse> LEAVE_TYPESAsync(WhoOffBot.Api.WhosOff.LEAVE_TYPESRequest request);
        
        // CODEGEN: Generating message contract since element name APIKEY from namespace http://publicapi.whosoff.com/WhosOffPublic.asmx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/DEPARTMENT_NAMES", ReplyAction="*")]
        WhoOffBot.Api.WhosOff.DEPARTMENT_NAMESResponse DEPARTMENT_NAMES(WhoOffBot.Api.WhosOff.DEPARTMENT_NAMESRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://publicapi.whosoff.com/WhosOffPublic.asmx/DEPARTMENT_NAMES", ReplyAction="*")]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.DEPARTMENT_NAMESResponse> DEPARTMENT_NAMESAsync(WhoOffBot.Api.WhosOff.DEPARTMENT_NAMESRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WhosOff", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class WhosOff {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public string APIKEY;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=1)]
        public string Start_Date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=2)]
        public string End_Date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=3)]
        public string Staff_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=4)]
        public string Department_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=5)]
        public string Leave_Type;
        
        public WhosOff() {
        }
        
        public WhosOff(string APIKEY, string Start_Date, string End_Date, string Staff_ID, string Department_Name, string Leave_Type) {
            this.APIKEY = APIKEY;
            this.Start_Date = Start_Date;
            this.End_Date = End_Date;
            this.Staff_ID = Staff_ID;
            this.Department_Name = Department_Name;
            this.Leave_Type = Leave_Type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WhosOffResponse", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class WhosOff1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public System.Xml.Linq.XElement WhosOffResult;
        
        public WhosOff1() {
        }
        
        public WhosOff1(System.Xml.Linq.XElement WhosOffResult) {
            this.WhosOffResult = WhosOffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WhosOffByCompany", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class WhosOffByCompany {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public string APIKEY;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=1)]
        public string Start_Date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=2)]
        public string End_Date;
        
        public WhosOffByCompany() {
        }
        
        public WhosOffByCompany(string APIKEY, string Start_Date, string End_Date) {
            this.APIKEY = APIKEY;
            this.Start_Date = Start_Date;
            this.End_Date = End_Date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WhosOffByCompanyResponse", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class WhosOffByCompany1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public System.Xml.Linq.XElement WhosOffByCompanyResult;
        
        public WhosOffByCompany1() {
        }
        
        public WhosOffByCompany1(System.Xml.Linq.XElement WhosOffByCompanyResult) {
            this.WhosOffByCompanyResult = WhosOffByCompanyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WhosOffByStaff", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class WhosOffByStaff {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public string APIKEY;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=1)]
        public string Start_Date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=2)]
        public string End_Date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=3)]
        public string Staff_ID;
        
        public WhosOffByStaff() {
        }
        
        public WhosOffByStaff(string APIKEY, string Start_Date, string End_Date, string Staff_ID) {
            this.APIKEY = APIKEY;
            this.Start_Date = Start_Date;
            this.End_Date = End_Date;
            this.Staff_ID = Staff_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WhosOffByStaffResponse", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class WhosOffByStaff1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public System.Xml.Linq.XElement WhosOffByStaffResult;
        
        public WhosOffByStaff1() {
        }
        
        public WhosOffByStaff1(System.Xml.Linq.XElement WhosOffByStaffResult) {
            this.WhosOffByStaffResult = WhosOffByStaffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WhosOffByDepartment", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class WhosOffByDepartment {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public string APIKEY;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=1)]
        public string Start_Date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=2)]
        public string End_Date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=3)]
        public string Department_Name;
        
        public WhosOffByDepartment() {
        }
        
        public WhosOffByDepartment(string APIKEY, string Start_Date, string End_Date, string Department_Name) {
            this.APIKEY = APIKEY;
            this.Start_Date = Start_Date;
            this.End_Date = End_Date;
            this.Department_Name = Department_Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WhosOffByDepartmentResponse", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class WhosOffByDepartment1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public System.Xml.Linq.XElement WhosOffByDepartmentResult;
        
        public WhosOffByDepartment1() {
        }
        
        public WhosOffByDepartment1(System.Xml.Linq.XElement WhosOffByDepartmentResult) {
            this.WhosOffByDepartmentResult = WhosOffByDepartmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WhosOffByLeaveType", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class WhosOffByLeaveType {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public string APIKEY;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=1)]
        public string Start_Date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=2)]
        public string End_Date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=3)]
        public string Leave_Type;
        
        public WhosOffByLeaveType() {
        }
        
        public WhosOffByLeaveType(string APIKEY, string Start_Date, string End_Date, string Leave_Type) {
            this.APIKEY = APIKEY;
            this.Start_Date = Start_Date;
            this.End_Date = End_Date;
            this.Leave_Type = Leave_Type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WhosOffByLeaveTypeResponse", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class WhosOffByLeaveType1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public System.Xml.Linq.XElement WhosOffByLeaveTypeResult;
        
        public WhosOffByLeaveType1() {
        }
        
        public WhosOffByLeaveType1(System.Xml.Linq.XElement WhosOffByLeaveTypeResult) {
            this.WhosOffByLeaveTypeResult = WhosOffByLeaveTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StaffDetails", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class StaffDetails {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public string APIKEY;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=1)]
        public string Department_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=2)]
        public string Staff_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=3)]
        public string Company_Year;
        
        public StaffDetails() {
        }
        
        public StaffDetails(string APIKEY, string Department_Name, string Staff_ID, string Company_Year) {
            this.APIKEY = APIKEY;
            this.Department_Name = Department_Name;
            this.Staff_ID = Staff_ID;
            this.Company_Year = Company_Year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StaffDetailsResponse", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class StaffDetails1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public System.Xml.Linq.XElement StaffDetailsResult;
        
        public StaffDetails1() {
        }
        
        public StaffDetails1(System.Xml.Linq.XElement StaffDetailsResult) {
            this.StaffDetailsResult = StaffDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StaffDetailsMinimum", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class StaffDetailsMinimum {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public string APIKEY;
        
        public StaffDetailsMinimum() {
        }
        
        public StaffDetailsMinimum(string APIKEY) {
            this.APIKEY = APIKEY;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StaffDetailsMinimumResponse", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class StaffDetailsMinimum1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public System.Xml.Linq.XElement StaffDetailsMinimumResult;
        
        public StaffDetailsMinimum1() {
        }
        
        public StaffDetailsMinimum1(System.Xml.Linq.XElement StaffDetailsMinimumResult) {
            this.StaffDetailsMinimumResult = StaffDetailsMinimumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Staff Details By StaffID", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class StaffDetailsByStaffID {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public string APIKEY;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=1)]
        public string Staff_ID;
        
        public StaffDetailsByStaffID() {
        }
        
        public StaffDetailsByStaffID(string APIKEY, string Staff_ID) {
            this.APIKEY = APIKEY;
            this.Staff_ID = Staff_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Staff Details By StaffIDResponse", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class StaffDetailsByStaffID1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Staff_x0020_Details_x0020_By_x0020_StaffIDResult", Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public System.Xml.Linq.XElement StaffDetailsByStaffIDResult;
        
        public StaffDetailsByStaffID1() {
        }
        
        public StaffDetailsByStaffID1(System.Xml.Linq.XElement StaffDetailsByStaffIDResult) {
            this.StaffDetailsByStaffIDResult = StaffDetailsByStaffIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Staff Details By StaffID inclucing Company Year", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class StaffDetailsByStaffIDinclucingCompanyYear {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public string APIKEY;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=1)]
        public string Staff_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=2)]
        public string Company_Year;
        
        public StaffDetailsByStaffIDinclucingCompanyYear() {
        }
        
        public StaffDetailsByStaffIDinclucingCompanyYear(string APIKEY, string Staff_ID, string Company_Year) {
            this.APIKEY = APIKEY;
            this.Staff_ID = Staff_ID;
            this.Company_Year = Company_Year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Staff Details By StaffID inclucing Company YearResponse", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class StaffDetailsByStaffIDinclucingCompanyYear1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Staff_x0020_Details_x0020_By_x0020_StaffID_x0020_inclucing_x0020_Company_x0020_Ye" +
            "arResult", Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public System.Xml.Linq.XElement StaffDetailsByStaffIDinclucingCompanyYearResult;
        
        public StaffDetailsByStaffIDinclucingCompanyYear1() {
        }
        
        public StaffDetailsByStaffIDinclucingCompanyYear1(System.Xml.Linq.XElement StaffDetailsByStaffIDinclucingCompanyYearResult) {
            this.StaffDetailsByStaffIDinclucingCompanyYearResult = StaffDetailsByStaffIDinclucingCompanyYearResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StaffDetailsByStaffID", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class StaffDetailsByStaffID2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public string APIKEY;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=1)]
        public string Department_Name;
        
        public StaffDetailsByStaffID2() {
        }
        
        public StaffDetailsByStaffID2(string APIKEY, string Department_Name) {
            this.APIKEY = APIKEY;
            this.Department_Name = Department_Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StaffDetailsByStaffIDResponse", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class StaffDetailsByStaffID3 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public System.Xml.Linq.XElement StaffDetailsByStaffIDResult;
        
        public StaffDetailsByStaffID3() {
        }
        
        public StaffDetailsByStaffID3(System.Xml.Linq.XElement StaffDetailsByStaffIDResult) {
            this.StaffDetailsByStaffIDResult = StaffDetailsByStaffIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Staff Details By StaffID including Company Year", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class StaffDetailsByStaffIDincludingCompanyYear {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public string APIKEY;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=1)]
        public string Department_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=2)]
        public string Company_Year;
        
        public StaffDetailsByStaffIDincludingCompanyYear() {
        }
        
        public StaffDetailsByStaffIDincludingCompanyYear(string APIKEY, string Department_Name, string Company_Year) {
            this.APIKEY = APIKEY;
            this.Department_Name = Department_Name;
            this.Company_Year = Company_Year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Staff Details By StaffID including Company YearResponse", WrapperNamespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", IsWrapped=true)]
    public partial class StaffDetailsByStaffIDincludingCompanyYear1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Staff_x0020_Details_x0020_By_x0020_StaffID_x0020_including_x0020_Company_x0020_Ye" +
            "arResult", Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public System.Xml.Linq.XElement StaffDetailsByStaffIDincludingCompanyYearResult;
        
        public StaffDetailsByStaffIDincludingCompanyYear1() {
        }
        
        public StaffDetailsByStaffIDincludingCompanyYear1(System.Xml.Linq.XElement StaffDetailsByStaffIDincludingCompanyYearResult) {
            this.StaffDetailsByStaffIDincludingCompanyYearResult = StaffDetailsByStaffIDincludingCompanyYearResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LEAVE_TYPESRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LEAVE_TYPES", Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public WhoOffBot.Api.WhosOff.LEAVE_TYPESRequestBody Body;
        
        public LEAVE_TYPESRequest() {
        }
        
        public LEAVE_TYPESRequest(WhoOffBot.Api.WhosOff.LEAVE_TYPESRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/")]
    public partial class LEAVE_TYPESRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string APIKEY;
        
        public LEAVE_TYPESRequestBody() {
        }
        
        public LEAVE_TYPESRequestBody(string APIKEY) {
            this.APIKEY = APIKEY;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LEAVE_TYPESResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LEAVE_TYPESResponse", Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public WhoOffBot.Api.WhosOff.LEAVE_TYPESResponseBody Body;
        
        public LEAVE_TYPESResponse() {
        }
        
        public LEAVE_TYPESResponse(WhoOffBot.Api.WhosOff.LEAVE_TYPESResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/")]
    public partial class LEAVE_TYPESResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement LEAVE_TYPESResult;
        
        public LEAVE_TYPESResponseBody() {
        }
        
        public LEAVE_TYPESResponseBody(System.Xml.Linq.XElement LEAVE_TYPESResult) {
            this.LEAVE_TYPESResult = LEAVE_TYPESResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DEPARTMENT_NAMESRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DEPARTMENT_NAMES", Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public WhoOffBot.Api.WhosOff.DEPARTMENT_NAMESRequestBody Body;
        
        public DEPARTMENT_NAMESRequest() {
        }
        
        public DEPARTMENT_NAMESRequest(WhoOffBot.Api.WhosOff.DEPARTMENT_NAMESRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/")]
    public partial class DEPARTMENT_NAMESRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string APIKEY;
        
        public DEPARTMENT_NAMESRequestBody() {
        }
        
        public DEPARTMENT_NAMESRequestBody(string APIKEY) {
            this.APIKEY = APIKEY;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DEPARTMENT_NAMESResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DEPARTMENT_NAMESResponse", Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/", Order=0)]
        public WhoOffBot.Api.WhosOff.DEPARTMENT_NAMESResponseBody Body;
        
        public DEPARTMENT_NAMESResponse() {
        }
        
        public DEPARTMENT_NAMESResponse(WhoOffBot.Api.WhosOff.DEPARTMENT_NAMESResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://publicapi.whosoff.com/WhosOffPublic.asmx/")]
    public partial class DEPARTMENT_NAMESResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement DEPARTMENT_NAMESResult;
        
        public DEPARTMENT_NAMESResponseBody() {
        }
        
        public DEPARTMENT_NAMESResponseBody(System.Xml.Linq.XElement DEPARTMENT_NAMESResult) {
            this.DEPARTMENT_NAMESResult = DEPARTMENT_NAMESResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WhosOffPublicSoapChannel : WhoOffBot.Api.WhosOff.WhosOffPublicSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WhosOffPublicSoapClient : System.ServiceModel.ClientBase<WhoOffBot.Api.WhosOff.WhosOffPublicSoap>, WhoOffBot.Api.WhosOff.WhosOffPublicSoap {
        
        public WhosOffPublicSoapClient() {
        }
        
        public WhosOffPublicSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WhosOffPublicSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WhosOffPublicSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WhosOffPublicSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WhoOffBot.Api.WhosOff.WhosOff1 WhoOffBot.Api.WhosOff.WhosOffPublicSoap.WHOSOFF(WhoOffBot.Api.WhosOff.WhosOff request) {
            return base.Channel.WHOSOFF(request);
        }
        
        public System.Xml.Linq.XElement WHOSOFF(string APIKEY, string Start_Date, string End_Date, string Staff_ID, string Department_Name, string Leave_Type) {
            WhoOffBot.Api.WhosOff.WhosOff inValue = new WhoOffBot.Api.WhosOff.WhosOff();
            inValue.APIKEY = APIKEY;
            inValue.Start_Date = Start_Date;
            inValue.End_Date = End_Date;
            inValue.Staff_ID = Staff_ID;
            inValue.Department_Name = Department_Name;
            inValue.Leave_Type = Leave_Type;
            WhoOffBot.Api.WhosOff.WhosOff1 retVal = ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).WHOSOFF(inValue);
            return retVal.WhosOffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.WhosOff1> WhoOffBot.Api.WhosOff.WhosOffPublicSoap.WHOSOFFAsync(WhoOffBot.Api.WhosOff.WhosOff request) {
            return base.Channel.WHOSOFFAsync(request);
        }
        
        public System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.WhosOff1> WHOSOFFAsync(string APIKEY, string Start_Date, string End_Date, string Staff_ID, string Department_Name, string Leave_Type) {
            WhoOffBot.Api.WhosOff.WhosOff inValue = new WhoOffBot.Api.WhosOff.WhosOff();
            inValue.APIKEY = APIKEY;
            inValue.Start_Date = Start_Date;
            inValue.End_Date = End_Date;
            inValue.Staff_ID = Staff_ID;
            inValue.Department_Name = Department_Name;
            inValue.Leave_Type = Leave_Type;
            return ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).WHOSOFFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WhoOffBot.Api.WhosOff.WhosOffByCompany1 WhoOffBot.Api.WhosOff.WhosOffPublicSoap.WHOSOFF1(WhoOffBot.Api.WhosOff.WhosOffByCompany request) {
            return base.Channel.WHOSOFF1(request);
        }
        
        public System.Xml.Linq.XElement WHOSOFF1(string APIKEY, string Start_Date, string End_Date) {
            WhoOffBot.Api.WhosOff.WhosOffByCompany inValue = new WhoOffBot.Api.WhosOff.WhosOffByCompany();
            inValue.APIKEY = APIKEY;
            inValue.Start_Date = Start_Date;
            inValue.End_Date = End_Date;
            WhoOffBot.Api.WhosOff.WhosOffByCompany1 retVal = ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).WHOSOFF1(inValue);
            return retVal.WhosOffByCompanyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.WhosOffByCompany1> WhoOffBot.Api.WhosOff.WhosOffPublicSoap.WHOSOFF1Async(WhoOffBot.Api.WhosOff.WhosOffByCompany request) {
            return base.Channel.WHOSOFF1Async(request);
        }
        
        public System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.WhosOffByCompany1> WHOSOFF1Async(string APIKEY, string Start_Date, string End_Date) {
            WhoOffBot.Api.WhosOff.WhosOffByCompany inValue = new WhoOffBot.Api.WhosOff.WhosOffByCompany();
            inValue.APIKEY = APIKEY;
            inValue.Start_Date = Start_Date;
            inValue.End_Date = End_Date;
            return ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).WHOSOFF1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WhoOffBot.Api.WhosOff.WhosOffByStaff1 WhoOffBot.Api.WhosOff.WhosOffPublicSoap.WHOSOFF_BY_STAFFID(WhoOffBot.Api.WhosOff.WhosOffByStaff request) {
            return base.Channel.WHOSOFF_BY_STAFFID(request);
        }
        
        public System.Xml.Linq.XElement WHOSOFF_BY_STAFFID(string APIKEY, string Start_Date, string End_Date, string Staff_ID) {
            WhoOffBot.Api.WhosOff.WhosOffByStaff inValue = new WhoOffBot.Api.WhosOff.WhosOffByStaff();
            inValue.APIKEY = APIKEY;
            inValue.Start_Date = Start_Date;
            inValue.End_Date = End_Date;
            inValue.Staff_ID = Staff_ID;
            WhoOffBot.Api.WhosOff.WhosOffByStaff1 retVal = ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).WHOSOFF_BY_STAFFID(inValue);
            return retVal.WhosOffByStaffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.WhosOffByStaff1> WhoOffBot.Api.WhosOff.WhosOffPublicSoap.WHOSOFF_BY_STAFFIDAsync(WhoOffBot.Api.WhosOff.WhosOffByStaff request) {
            return base.Channel.WHOSOFF_BY_STAFFIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.WhosOffByStaff1> WHOSOFF_BY_STAFFIDAsync(string APIKEY, string Start_Date, string End_Date, string Staff_ID) {
            WhoOffBot.Api.WhosOff.WhosOffByStaff inValue = new WhoOffBot.Api.WhosOff.WhosOffByStaff();
            inValue.APIKEY = APIKEY;
            inValue.Start_Date = Start_Date;
            inValue.End_Date = End_Date;
            inValue.Staff_ID = Staff_ID;
            return ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).WHOSOFF_BY_STAFFIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WhoOffBot.Api.WhosOff.WhosOffByDepartment1 WhoOffBot.Api.WhosOff.WhosOffPublicSoap.WHOSOFF_BY_DEPARTMENT(WhoOffBot.Api.WhosOff.WhosOffByDepartment request) {
            return base.Channel.WHOSOFF_BY_DEPARTMENT(request);
        }
        
        public System.Xml.Linq.XElement WHOSOFF_BY_DEPARTMENT(string APIKEY, string Start_Date, string End_Date, string Department_Name) {
            WhoOffBot.Api.WhosOff.WhosOffByDepartment inValue = new WhoOffBot.Api.WhosOff.WhosOffByDepartment();
            inValue.APIKEY = APIKEY;
            inValue.Start_Date = Start_Date;
            inValue.End_Date = End_Date;
            inValue.Department_Name = Department_Name;
            WhoOffBot.Api.WhosOff.WhosOffByDepartment1 retVal = ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).WHOSOFF_BY_DEPARTMENT(inValue);
            return retVal.WhosOffByDepartmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.WhosOffByDepartment1> WhoOffBot.Api.WhosOff.WhosOffPublicSoap.WHOSOFF_BY_DEPARTMENTAsync(WhoOffBot.Api.WhosOff.WhosOffByDepartment request) {
            return base.Channel.WHOSOFF_BY_DEPARTMENTAsync(request);
        }
        
        public System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.WhosOffByDepartment1> WHOSOFF_BY_DEPARTMENTAsync(string APIKEY, string Start_Date, string End_Date, string Department_Name) {
            WhoOffBot.Api.WhosOff.WhosOffByDepartment inValue = new WhoOffBot.Api.WhosOff.WhosOffByDepartment();
            inValue.APIKEY = APIKEY;
            inValue.Start_Date = Start_Date;
            inValue.End_Date = End_Date;
            inValue.Department_Name = Department_Name;
            return ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).WHOSOFF_BY_DEPARTMENTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WhoOffBot.Api.WhosOff.WhosOffByLeaveType1 WhoOffBot.Api.WhosOff.WhosOffPublicSoap.WHOSOFF_BY_LEAVE_TYPE(WhoOffBot.Api.WhosOff.WhosOffByLeaveType request) {
            return base.Channel.WHOSOFF_BY_LEAVE_TYPE(request);
        }
        
        public System.Xml.Linq.XElement WHOSOFF_BY_LEAVE_TYPE(string APIKEY, string Start_Date, string End_Date, string Leave_Type) {
            WhoOffBot.Api.WhosOff.WhosOffByLeaveType inValue = new WhoOffBot.Api.WhosOff.WhosOffByLeaveType();
            inValue.APIKEY = APIKEY;
            inValue.Start_Date = Start_Date;
            inValue.End_Date = End_Date;
            inValue.Leave_Type = Leave_Type;
            WhoOffBot.Api.WhosOff.WhosOffByLeaveType1 retVal = ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).WHOSOFF_BY_LEAVE_TYPE(inValue);
            return retVal.WhosOffByLeaveTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.WhosOffByLeaveType1> WhoOffBot.Api.WhosOff.WhosOffPublicSoap.WHOSOFF_BY_LEAVE_TYPEAsync(WhoOffBot.Api.WhosOff.WhosOffByLeaveType request) {
            return base.Channel.WHOSOFF_BY_LEAVE_TYPEAsync(request);
        }
        
        public System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.WhosOffByLeaveType1> WHOSOFF_BY_LEAVE_TYPEAsync(string APIKEY, string Start_Date, string End_Date, string Leave_Type) {
            WhoOffBot.Api.WhosOff.WhosOffByLeaveType inValue = new WhoOffBot.Api.WhosOff.WhosOffByLeaveType();
            inValue.APIKEY = APIKEY;
            inValue.Start_Date = Start_Date;
            inValue.End_Date = End_Date;
            inValue.Leave_Type = Leave_Type;
            return ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).WHOSOFF_BY_LEAVE_TYPEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WhoOffBot.Api.WhosOff.StaffDetails1 WhoOffBot.Api.WhosOff.WhosOffPublicSoap.STAFF_DETAILS(WhoOffBot.Api.WhosOff.StaffDetails request) {
            return base.Channel.STAFF_DETAILS(request);
        }
        
        public System.Xml.Linq.XElement STAFF_DETAILS(string APIKEY, string Department_Name, string Staff_ID, string Company_Year) {
            WhoOffBot.Api.WhosOff.StaffDetails inValue = new WhoOffBot.Api.WhosOff.StaffDetails();
            inValue.APIKEY = APIKEY;
            inValue.Department_Name = Department_Name;
            inValue.Staff_ID = Staff_ID;
            inValue.Company_Year = Company_Year;
            WhoOffBot.Api.WhosOff.StaffDetails1 retVal = ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).STAFF_DETAILS(inValue);
            return retVal.StaffDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.StaffDetails1> WhoOffBot.Api.WhosOff.WhosOffPublicSoap.STAFF_DETAILSAsync(WhoOffBot.Api.WhosOff.StaffDetails request) {
            return base.Channel.STAFF_DETAILSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.StaffDetails1> STAFF_DETAILSAsync(string APIKEY, string Department_Name, string Staff_ID, string Company_Year) {
            WhoOffBot.Api.WhosOff.StaffDetails inValue = new WhoOffBot.Api.WhosOff.StaffDetails();
            inValue.APIKEY = APIKEY;
            inValue.Department_Name = Department_Name;
            inValue.Staff_ID = Staff_ID;
            inValue.Company_Year = Company_Year;
            return ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).STAFF_DETAILSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WhoOffBot.Api.WhosOff.StaffDetailsMinimum1 WhoOffBot.Api.WhosOff.WhosOffPublicSoap.STAFF_DETAILS1(WhoOffBot.Api.WhosOff.StaffDetailsMinimum request) {
            return base.Channel.STAFF_DETAILS1(request);
        }
        
        public System.Xml.Linq.XElement STAFF_DETAILS1(string APIKEY) {
            WhoOffBot.Api.WhosOff.StaffDetailsMinimum inValue = new WhoOffBot.Api.WhosOff.StaffDetailsMinimum();
            inValue.APIKEY = APIKEY;
            WhoOffBot.Api.WhosOff.StaffDetailsMinimum1 retVal = ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).STAFF_DETAILS1(inValue);
            return retVal.StaffDetailsMinimumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.StaffDetailsMinimum1> WhoOffBot.Api.WhosOff.WhosOffPublicSoap.STAFF_DETAILS1Async(WhoOffBot.Api.WhosOff.StaffDetailsMinimum request) {
            return base.Channel.STAFF_DETAILS1Async(request);
        }
        
        public System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.StaffDetailsMinimum1> STAFF_DETAILS1Async(string APIKEY) {
            WhoOffBot.Api.WhosOff.StaffDetailsMinimum inValue = new WhoOffBot.Api.WhosOff.StaffDetailsMinimum();
            inValue.APIKEY = APIKEY;
            return ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).STAFF_DETAILS1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WhoOffBot.Api.WhosOff.StaffDetailsByStaffID1 WhoOffBot.Api.WhosOff.WhosOffPublicSoap.STAFF_DETAILS_BY_STAFFID(WhoOffBot.Api.WhosOff.StaffDetailsByStaffID request) {
            return base.Channel.STAFF_DETAILS_BY_STAFFID(request);
        }
        
        public System.Xml.Linq.XElement STAFF_DETAILS_BY_STAFFID(string APIKEY, string Staff_ID) {
            WhoOffBot.Api.WhosOff.StaffDetailsByStaffID inValue = new WhoOffBot.Api.WhosOff.StaffDetailsByStaffID();
            inValue.APIKEY = APIKEY;
            inValue.Staff_ID = Staff_ID;
            WhoOffBot.Api.WhosOff.StaffDetailsByStaffID1 retVal = ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).STAFF_DETAILS_BY_STAFFID(inValue);
            return retVal.StaffDetailsByStaffIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.StaffDetailsByStaffID1> WhoOffBot.Api.WhosOff.WhosOffPublicSoap.STAFF_DETAILS_BY_STAFFIDAsync(WhoOffBot.Api.WhosOff.StaffDetailsByStaffID request) {
            return base.Channel.STAFF_DETAILS_BY_STAFFIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.StaffDetailsByStaffID1> STAFF_DETAILS_BY_STAFFIDAsync(string APIKEY, string Staff_ID) {
            WhoOffBot.Api.WhosOff.StaffDetailsByStaffID inValue = new WhoOffBot.Api.WhosOff.StaffDetailsByStaffID();
            inValue.APIKEY = APIKEY;
            inValue.Staff_ID = Staff_ID;
            return ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).STAFF_DETAILS_BY_STAFFIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDinclucingCompanyYear1 WhoOffBot.Api.WhosOff.WhosOffPublicSoap.STAFF_DETAILS_BY_STAFFID1(WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDinclucingCompanyYear request) {
            return base.Channel.STAFF_DETAILS_BY_STAFFID1(request);
        }
        
        public System.Xml.Linq.XElement STAFF_DETAILS_BY_STAFFID1(string APIKEY, string Staff_ID, string Company_Year) {
            WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDinclucingCompanyYear inValue = new WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDinclucingCompanyYear();
            inValue.APIKEY = APIKEY;
            inValue.Staff_ID = Staff_ID;
            inValue.Company_Year = Company_Year;
            WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDinclucingCompanyYear1 retVal = ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).STAFF_DETAILS_BY_STAFFID1(inValue);
            return retVal.StaffDetailsByStaffIDinclucingCompanyYearResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDinclucingCompanyYear1> WhoOffBot.Api.WhosOff.WhosOffPublicSoap.STAFF_DETAILS_BY_STAFFID1Async(WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDinclucingCompanyYear request) {
            return base.Channel.STAFF_DETAILS_BY_STAFFID1Async(request);
        }
        
        public System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDinclucingCompanyYear1> STAFF_DETAILS_BY_STAFFID1Async(string APIKEY, string Staff_ID, string Company_Year) {
            WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDinclucingCompanyYear inValue = new WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDinclucingCompanyYear();
            inValue.APIKEY = APIKEY;
            inValue.Staff_ID = Staff_ID;
            inValue.Company_Year = Company_Year;
            return ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).STAFF_DETAILS_BY_STAFFID1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WhoOffBot.Api.WhosOff.StaffDetailsByStaffID3 WhoOffBot.Api.WhosOff.WhosOffPublicSoap.STAFF_DETAILS_BY_DEPARTMENT(WhoOffBot.Api.WhosOff.StaffDetailsByStaffID2 request) {
            return base.Channel.STAFF_DETAILS_BY_DEPARTMENT(request);
        }
        
        public System.Xml.Linq.XElement STAFF_DETAILS_BY_DEPARTMENT(string APIKEY, string Department_Name) {
            WhoOffBot.Api.WhosOff.StaffDetailsByStaffID2 inValue = new WhoOffBot.Api.WhosOff.StaffDetailsByStaffID2();
            inValue.APIKEY = APIKEY;
            inValue.Department_Name = Department_Name;
            WhoOffBot.Api.WhosOff.StaffDetailsByStaffID3 retVal = ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).STAFF_DETAILS_BY_DEPARTMENT(inValue);
            return retVal.StaffDetailsByStaffIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.StaffDetailsByStaffID3> WhoOffBot.Api.WhosOff.WhosOffPublicSoap.STAFF_DETAILS_BY_DEPARTMENTAsync(WhoOffBot.Api.WhosOff.StaffDetailsByStaffID2 request) {
            return base.Channel.STAFF_DETAILS_BY_DEPARTMENTAsync(request);
        }
        
        public System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.StaffDetailsByStaffID3> STAFF_DETAILS_BY_DEPARTMENTAsync(string APIKEY, string Department_Name) {
            WhoOffBot.Api.WhosOff.StaffDetailsByStaffID2 inValue = new WhoOffBot.Api.WhosOff.StaffDetailsByStaffID2();
            inValue.APIKEY = APIKEY;
            inValue.Department_Name = Department_Name;
            return ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).STAFF_DETAILS_BY_DEPARTMENTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDincludingCompanyYear1 WhoOffBot.Api.WhosOff.WhosOffPublicSoap.STAFF_DETAILS_BY_DEPARTMENT1(WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDincludingCompanyYear request) {
            return base.Channel.STAFF_DETAILS_BY_DEPARTMENT1(request);
        }
        
        public System.Xml.Linq.XElement STAFF_DETAILS_BY_DEPARTMENT1(string APIKEY, string Department_Name, string Company_Year) {
            WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDincludingCompanyYear inValue = new WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDincludingCompanyYear();
            inValue.APIKEY = APIKEY;
            inValue.Department_Name = Department_Name;
            inValue.Company_Year = Company_Year;
            WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDincludingCompanyYear1 retVal = ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).STAFF_DETAILS_BY_DEPARTMENT1(inValue);
            return retVal.StaffDetailsByStaffIDincludingCompanyYearResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDincludingCompanyYear1> WhoOffBot.Api.WhosOff.WhosOffPublicSoap.STAFF_DETAILS_BY_DEPARTMENT1Async(WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDincludingCompanyYear request) {
            return base.Channel.STAFF_DETAILS_BY_DEPARTMENT1Async(request);
        }
        
        public System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDincludingCompanyYear1> STAFF_DETAILS_BY_DEPARTMENT1Async(string APIKEY, string Department_Name, string Company_Year) {
            WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDincludingCompanyYear inValue = new WhoOffBot.Api.WhosOff.StaffDetailsByStaffIDincludingCompanyYear();
            inValue.APIKEY = APIKEY;
            inValue.Department_Name = Department_Name;
            inValue.Company_Year = Company_Year;
            return ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).STAFF_DETAILS_BY_DEPARTMENT1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WhoOffBot.Api.WhosOff.LEAVE_TYPESResponse WhoOffBot.Api.WhosOff.WhosOffPublicSoap.LEAVE_TYPES(WhoOffBot.Api.WhosOff.LEAVE_TYPESRequest request) {
            return base.Channel.LEAVE_TYPES(request);
        }
        
        public System.Xml.Linq.XElement LEAVE_TYPES(string APIKEY) {
            WhoOffBot.Api.WhosOff.LEAVE_TYPESRequest inValue = new WhoOffBot.Api.WhosOff.LEAVE_TYPESRequest();
            inValue.Body = new WhoOffBot.Api.WhosOff.LEAVE_TYPESRequestBody();
            inValue.Body.APIKEY = APIKEY;
            WhoOffBot.Api.WhosOff.LEAVE_TYPESResponse retVal = ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).LEAVE_TYPES(inValue);
            return retVal.Body.LEAVE_TYPESResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.LEAVE_TYPESResponse> WhoOffBot.Api.WhosOff.WhosOffPublicSoap.LEAVE_TYPESAsync(WhoOffBot.Api.WhosOff.LEAVE_TYPESRequest request) {
            return base.Channel.LEAVE_TYPESAsync(request);
        }
        
        public System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.LEAVE_TYPESResponse> LEAVE_TYPESAsync(string APIKEY) {
            WhoOffBot.Api.WhosOff.LEAVE_TYPESRequest inValue = new WhoOffBot.Api.WhosOff.LEAVE_TYPESRequest();
            inValue.Body = new WhoOffBot.Api.WhosOff.LEAVE_TYPESRequestBody();
            inValue.Body.APIKEY = APIKEY;
            return ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).LEAVE_TYPESAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WhoOffBot.Api.WhosOff.DEPARTMENT_NAMESResponse WhoOffBot.Api.WhosOff.WhosOffPublicSoap.DEPARTMENT_NAMES(WhoOffBot.Api.WhosOff.DEPARTMENT_NAMESRequest request) {
            return base.Channel.DEPARTMENT_NAMES(request);
        }
        
        public System.Xml.Linq.XElement DEPARTMENT_NAMES(string APIKEY) {
            WhoOffBot.Api.WhosOff.DEPARTMENT_NAMESRequest inValue = new WhoOffBot.Api.WhosOff.DEPARTMENT_NAMESRequest();
            inValue.Body = new WhoOffBot.Api.WhosOff.DEPARTMENT_NAMESRequestBody();
            inValue.Body.APIKEY = APIKEY;
            WhoOffBot.Api.WhosOff.DEPARTMENT_NAMESResponse retVal = ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).DEPARTMENT_NAMES(inValue);
            return retVal.Body.DEPARTMENT_NAMESResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.DEPARTMENT_NAMESResponse> WhoOffBot.Api.WhosOff.WhosOffPublicSoap.DEPARTMENT_NAMESAsync(WhoOffBot.Api.WhosOff.DEPARTMENT_NAMESRequest request) {
            return base.Channel.DEPARTMENT_NAMESAsync(request);
        }
        
        public System.Threading.Tasks.Task<WhoOffBot.Api.WhosOff.DEPARTMENT_NAMESResponse> DEPARTMENT_NAMESAsync(string APIKEY) {
            WhoOffBot.Api.WhosOff.DEPARTMENT_NAMESRequest inValue = new WhoOffBot.Api.WhosOff.DEPARTMENT_NAMESRequest();
            inValue.Body = new WhoOffBot.Api.WhosOff.DEPARTMENT_NAMESRequestBody();
            inValue.Body.APIKEY = APIKEY;
            return ((WhoOffBot.Api.WhosOff.WhosOffPublicSoap)(this)).DEPARTMENT_NAMESAsync(inValue);
        }
    }
}
